apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: nginx-helm-chart
    releaseName: nginx-prod
    version: 0.1.0
    repo: "file://../../base/nginx-helm-chart"
    valuesFile: values-prod.yaml
